from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Case_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Case_tab.setGeometry(QtCore.QRect(10, 0, 621, 441))
        self.Case_tab.setObjectName("Case_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.caseTable = QtWidgets.QTableWidget(self.tab)
        self.caseTable.setGeometry(QtCore.QRect(0, 0, 611, 301))
        self.caseTable.setObjectName("caseTable")
        self.caseTable.setColumnCount(0)
        self.caseTable.setRowCount(0)
        self.addCaseButton = QtWidgets.QPushButton(self.tab)
        self.addCaseButton.setGeometry(QtCore.QRect(20, 370, 111, 32))
        self.addCaseButton.setObjectName("addCaseButton")
        self.deleteCaseButton = QtWidgets.QPushButton(self.tab)
        self.deleteCaseButton.setGeometry(QtCore.QRect(180, 370, 111, 32))
        self.deleteCaseButton.setObjectName("deleteCaseButton")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 330, 191, 32))
        self.comboBox.setObjectName("comboBox")
        self.Case_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addProformaButton = QtWidgets.QPushButton(self.tab_2)
        self.addProformaButton.setGeometry(QtCore.QRect(30, 370, 141, 32))
        self.addProformaButton.setObjectName("addProformaButton")
        self.deleteProformaButton = QtWidgets.QPushButton(self.tab_2)
        self.deleteProformaButton.setGeometry(QtCore.QRect(190, 370, 141, 32))
        self.deleteProformaButton.setObjectName("deleteProformaButton")
        self.proformaTable = QtWidgets.QTableWidget(self.tab_2)
        self.proformaTable.setGeometry(QtCore.QRect(0, 0, 611, 311))
        self.proformaTable.setObjectName("proformaTable")
        self.proformaTable.setColumnCount(0)
        self.proformaTable.setRowCount(0)
        self.caseNumberComboBox = QtWidgets.QComboBox(self.tab_2)
        self.caseNumberComboBox.setGeometry(QtCore.QRect(30, 320, 161, 32))
        self.caseNumberComboBox.setObjectName("caseNumberComboBox")
        self.Case_tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.addClientButton = QtWidgets.QPushButton(self.tab_3)
        self.addClientButton.setGeometry(QtCore.QRect(30, 360, 131, 32))
        self.addClientButton.setObjectName("addClientButton")
        self.deleteClientButton = QtWidgets.QPushButton(self.tab_3)
        self.deleteClientButton.setGeometry(QtCore.QRect(180, 360, 131, 32))
        self.deleteClientButton.setObjectName("deleteClientButton")
        self.clientTable = QtWidgets.QTableWidget(self.tab_3)
        self.clientTable.setGeometry(QtCore.QRect(0, 0, 621, 311))
        self.clientTable.setObjectName("clientTable")
        self.clientTable.setColumnCount(0)
        self.clientTable.setRowCount(0)
        self.Case_tab.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Case_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addCaseButton.setText(_translate("MainWindow", "Добавить дело"))
        self.deleteCaseButton.setText(_translate("MainWindow", "Удалить дело"))
        self.Case_tab.setTabText(self.Case_tab.indexOf(self.tab), _translate("MainWindow", "Номера дел"))
        self.addProformaButton.setText(_translate("MainWindow", "Добавить проформу"))
        self.deleteProformaButton.setText(_translate("MainWindow", "Удалить проформу"))
        self.Case_tab.setTabText(self.Case_tab.indexOf(self.tab_2), _translate("MainWindow", "Номера проформ"))
        self.addClientButton.setText(_translate("MainWindow", "Добавить клиента"))
        self.deleteClientButton.setText(_translate("MainWindow", "Удалить клиента"))
        self.Case_tab.setTabText(self.Case_tab.indexOf(self.tab_3), _translate("MainWindow", "Клиенты"))
